--migration step 1: creating the table. As mentioned, each migration step
--has 2 parts. The SQL script to execute the schema change and the script to
--undo those changes (001.undo.create)

CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);

