--set up the users table first

CREATE TABLE blogful_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT,
  nickname TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

--alter articles table to add the author column so we can set up the 
--FK restraint between author and id of users

ALTER TABLE blogful_articles
  ADD COLUMN
    author INTEGER REFERENCES blogful_users(id)
    ON DELETE SET NULL;