--create comments table with the 2 FK restraints

CREATE TABLE blogful_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    text TEXT NOT NULL,
    date_commented TIMESTAMPTZ DEFAULT now() NOT NULL,
    article_id INTEGER
        REFERENCES blogful_articles(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES blogful_users(id) ON DELETE CASCADE NOT NULL
);

--A foreign key with cascade delete means that if a record in the parent 
--table is deleted, then the corresponding records in the child table will 
--automatically be deleted. i.e. folders and notes. if a folder with 3 notes gets
--deleted, those notes corresponding to that folder will also get deleted

